# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Gregg Bernstein"
description: > # this means to ignore newlines until "email:"
   User & Product Researcher // Writer // Speaker

email: me@gregg.io
#blog logo
logo: "/assets/images/gb_logo.png"
# blog cover
cover: "/assets/images/cover.jpg"

name: 'Gregg Bernstein'
author: 'Gregg Bernstein'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://gregg.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@greggcorp'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/greggcorp
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/greggcorp
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
