# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Site settings
title: "Gregg Bernstein | gregg.io"
email: me@gregg.io
name: 'Gregg Bernstein'
author: 'Gregg Bernstein'
description: > # this means to ignore newlines until "baseurl:"
  User &amp; Product Researcher &bull; Writer &amp; Editor &bull; Speaker &amp; Educator
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregg.io" # the base hostname & protocol for your site
twitter_username: greggcorp
github_username:

# Google services
google_analytics: UA-79596449-1

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
